services:
    database:
        image: mysql:8.0
        container_name: vehicle_loans_database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            APP_DEBUG: ${APP_DEBUG}
        volumes:
            - database_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 5s
            retries: 5
        ports:
            - "3306:3306"

    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        container_name: vehicle_loans_app
        restart: unless-stopped
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www/html
        environment:
            - DB_HOST=${DB_HOST}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            database:
                condition: service_healthy

    nginx:
        image: nginx:alpine
        container_name: vehicle_loans_nginx
        restart: unless-stopped
        ports:
            - '8080:80'
            - '443:443'
        volumes:
            - ./:/var/www/html
            - ./.cicd/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

volumes:
    database_data:

